# Generated by Django 5.0.6 on 2024-05-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book_lan',
            new_name='book_lang',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(default='default_img/default_book_img.png', upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(),
        ),
    ]
