# Generated by Django 5.0.6 on 2024-05-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_book_lan_books_book_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(default='default_img/default_dori_img.png', upload_to='books/'),
        ),
    ]
